#!/bin/python

import os
import platform
import sys
import shutil

windows = platform.system() == 'Windows'
linux = platform.system() == 'Linux'


def init(force_reinit):
    root = os.getcwd()
    os.system("git submodule update --init --recursive")
    system = platform.system()

    if os.path.exists("./pico/tools/toolchain/bin/arm-none-eabi-gcc") and not force_reinit:
        print("Toolchain already installed.")
    else:
        if system == "Windows":
            # This does not exist yet so it does not work
            os.system(".\\pico\\install_toolchain.bat")
        else:
            os.system("./pico/install_toolchain")

    if os.path.exists("./pc/src/gui/SDL_ttf/external/freetype/") and not force_reinit:
        print("SDL_ttf dependencies already installed.")
    else:
        if system == "Windows":
            os.system(".\\pc\\src\\gui\\SDL_ttf\\external\\Get-GitModules.ps1")
        else:
            os.system("./pc/src/gui/SDL_ttf/external/download.sh")

    os.chdir("pico/picotool")
    if not os.path.exists("build"):
        os.mkdir("build")
    os.chdir("build")

    if system == "Windows":
        os.system("cmake .. -G \"MinGW Makefiles\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\\..\\tools\\picotool -DCMAKE_FLAT_INSTALL=1")
        os.system("make")
        os.sysmtem("make install")
    else:
        os.system(
            "cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../tools/picotool -DCMAKE_FLAT_INSTALL=1")
        os.system("ninja -j4")
        os.system("ninja install")
    os.chdir(root)


def build_project(root, path):
    os.chdir(path)
    if not os.path.isdir("build"):
        os.mkdir("build")
    os.chdir("build")

    cmake_command = 'cmake ..'
    make_command = ''

    if windows:
        make_command = 'make'
        cmake_command += ' -G "MinGW Makefiles"'
        os.system(cmake_command)
    elif linux:
        make_command = 'ninja -j8'
        cmake_command += ' -G Ninja'
        os.system(cmake_command)

    if make_command == '':
        os.chdir(root)
        return

    os.system(make_command)
    os.chdir(root)


def rebuild_project(root, path):
    os.chdir(path)
    if os.path.isdir("build"):
        shutil.rmtree("build")
    build_project(root, os.getcwd())


def build(mode):
    root = os.getcwd()
    if mode == "b":
        build_project(root, "pico/drone")
        build_project(
            root, "pc")
        build_project(
            root, "pico/transceiver")
    else:
        rebuild_project(root, "pico/drone")
        rebuild_project(
            root, "pc")
        rebuild_project(
            root, "pico/transceiver")


def main():
    build_type = ""
    force_reinit = False
    if len(sys.argv) > 1:
        if 'r' in sys.argv:
            build_type = "r"
        else:
            build_type = "b"
        if 'i' in sys.argv:
            force_reinit = True
        if 'h' in sys.argv:
            print("Usage: python build.py [r|b] [h]")
            print("r: rebuild all projects")
            print("b: build only changed files (default)")
            print("h: display this help message")
            return
    else:
        build_type = "b"

    init(force_reinit)
    build(build_type)

    if not os.path.isdir("bin"):
        os.mkdir("bin")

    if linux:
        shutil.copyfile("./pc/build/pc_app", "bin/pc_app")
    else:
        shutil.copyfile("./pc/build/pc_app.exe", "bin/pc_app.exe")
    shutil.copyfile("./pico/drone/build/drone.uf2", "bin/drone.uf2")
    shutil.copyfile("./pico/transceiver/build/transceiver.uf2",
                    "bin/transceiver.uf2")
    if linux:
        os.system("chmod +x bin/pc_app")


if __name__ == '__main__':
    main()
