#!/bin/python

import os
import platform
import sys
import shutil

windows = platform.system() == 'Windows'
linux = platform.system() == 'Linux'


def init(force_reinit):
    root = os.getcwd()
    os.system("git submodule update --init --recursive")
    system = platform.system()

    if os.path.exists("./pico/tools/toolchain/bin/arm-none-eabi-gcc") and not force_reinit:
        print("Toolchain already installed.")
    else:
        if system == "Windows":
            # This does not exist yet so it does not work
            os.system(".\\pico\\install_toolchain.bat")
        else:
            os.system("./pico/install_toolchain")

    if os.path.exists("./pc/src/gui/SDL_ttf/external/freetype/") and not force_reinit:
        print("SDL_ttf dependencies already installed.")
    else:
        if system == "Windows":
            os.system(".\\pc\\src\\gui\\SDL_ttf\\external\\Get-GitModules.ps1")
        else:
            os.system("./pc/src/gui/SDL_ttf/external/download.sh")

    os.chdir("pico/picotool")
    if not os.path.exists("build"):
        os.mkdir("build")
    os.chdir("build")

    if system == "Windows":
        os.system("cmake .. -G \"MinGW Makefiles\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\\..\\tools\\picotool -DCMAKE_FLAT_INSTALL=1")
        os.system("make")
        os.sysmtem("make install")
    else:
        os.system(
            "cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../tools/picotool -DCMAKE_FLAT_INSTALL=1")
        os.system("ninja -j4")
        os.system("ninja install")
    os.chdir(root)


def build_project(root, path):
    os.chdir(path)
    if not os.path.isdir("build"):
        os.mkdir("build")
    os.chdir("build")

    cmake_command = 'cmake ..'
    make_command = ''

    if windows:
        make_command = 'make'
        cmake_command += ' -G "MinGW Makefiles"'
        os.system(cmake_command)
    elif linux:
        make_command = 'ninja -j8'
        cmake_command += ' -G Ninja'
        os.system(cmake_command)

    if make_command == '':
        os.chdir(root)
        return

    os.system(make_command)
    os.chdir(root)


def rebuild_project(root, path):
    os.chdir(path)
    if os.path.isdir("build"):
        shutil.rmtree("build")
    build_project(root, os.getcwd())


def build_pc(mode):
    root = os.getcwd()
    if mode == "b":
        build_project(root, "pc")
    else:
        rebuild_project(root, "pc")

    if linux:
        shutil.copyfile("./pc/build/pc_app", "bin/pc_app")
    else:
        shutil.copyfile("./pc/build/pc_app.exe", "bin/pc_app.exe")
    if os.path.isdir("./shaders"):
        shutil.rmtree("./shaders")
    shutil.copytree("./pc/shaders", "./shaders")
    if os.path.isdir("./fonts"):
        shutil.rmtree("./fonts")
    shutil.copytree("./pc/fonts", "./fonts")
    if linux:
        os.system("chmod +x bin/pc_app")


def build_drone(mode):
    root = os.getcwd()
    if mode == "b":
        build_project(root, "pico/drone")
    else:
        rebuild_project(root, "pico/drone")
    shutil.copyfile("./pico/drone/build/drone.uf2", "bin/drone.uf2")


def build_transceiver(mode):
    root = os.getcwd()
    if mode == "b":
        build_project(root, "pico/transceiver")
    else:
        rebuild_project(root, "pico/transceiver")
    shutil.copyfile("./pico/transceiver/build/transceiver.uf2",
                    "bin/transceiver.uf2")


def build(mode, project):
    if not os.path.isdir("bin"):
        os.mkdir("bin")
    if project["pc"] or project is None:
        build_pc(mode)
    if project["drone"] or project is None:
        build_drone(mode)
    if project["transceiver"] or project is None:
        build_transceiver(mode)


def main():
    build_type = ""
    force_reinit = False
    project = {"pc": False, "drone": False, "transceiver": False}
    if len(sys.argv) == 1:
        build_type = "b"
        init(force_reinit)
        build(build_type, None)
        return

    if 'r' in sys.argv:
        build_type = "r"
    else:
        build_type = "b"
    if 'i' in sys.argv:
        force_reinit = True
    if 'h' in sys.argv:
        print("Usage: ./build <project> [r] [h] [i]")
        print("i: force re-initialization of submodules and toolchains")
        print("r: rebuild all projects")
        print("h: display this help message")
        print("project: specify which project to build. Options are 'pc', 'drone', and 'transceiver'.")
        print("If no project is specified, all projects will be built.")
        return
    if 'pc' in sys.argv:
        project["pc"] = True
    if 'drone' in sys.argv:
        project["drone"] = True
    if 'transceiver' in sys.argv:
        project["transceiver"] = True
    if not (project["pc"] or project["drone"] or project["transceiver"]):
        project["pc"] = True
        project["drone"] = True
        project["transceiver"] = True
    if sys.argv[1] not in ['pc', 'drone', 'transceiver', 'r', 'i', 'h']:
        print(f"Unknown argument: {sys.argv[1]}. Use 'h' for help.")
        return

    init(force_reinit)
    build(build_type, project)


if __name__ == '__main__':
    main()
