#!/bin/python

import os
import platform
import sys
import shutil

windows = platform.system() == 'Windows'
linux = platform.system() == 'Linux'


def build_project(root, path):
    os.chdir(path)
    if not os.path.isdir("build"):
        os.mkdir("build")
    os.chdir("build")

    cmake_command = 'cmake ..'
    make_command = ''

    if windows:
        make_command = 'make'
        cmake_command += ' -G "MinGW Makefiles"'
        os.system(cmake_command)
    elif linux:
        make_command = 'ninja'
        cmake_command += ' -G Ninja'
        os.system(cmake_command)

    if make_command == '':
        os.chdir(root)
        return

    os.system(make_command)
    os.chdir(root)


def rebuild_project(root, path):
    os.chdir(path)
    if os.path.isdir("build"):
        shutil.rmtree("build")
    build_project(root, os.getcwd())


def build(mode):
    root = os.getcwd()
    if mode == "b":
        build_project(root, "pico/drone")
        build_project(
            root, "pc")
        build_project(
            root, "pico/transceiver")
    else:
        rebuild_project(root, "pico/drone")
        rebuild_project(
            root, "pc")
        rebuild_project(
            root, "pico/transceiver")


def main():
    build_type = ""
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        if arg[0] == 'b':
            build_type = "b"
        if arg[0] == 'r':
            build_type = "r"
    if build_type == "":
        while build_type != "b" and build_type != "r":
            build_type = input("Type 'b' for build, 'r' for rebuild\n")

    build(build_type)

    if not os.path.isdir("bin"):
        os.mkdir("bin")

    if linux:
        shutil.copyfile("./pc/build/pc_app", "bin/pc_app")
    else:
        shutil.copyfile("./pc/build/pc_app.exe", "bin/pc_app.exe")
    shutil.copyfile("./pico/drone/build/drone.uf2", "bin/drone.uf2")
    shutil.copyfile("./pico/transceiver/build/transceiver.uf2",
                    "bin/transceiver.uf2")
    if linux:
        os.system("chmod +x bin/pc_app")


if __name__ == '__main__':
    main()
