#!/bin/python

import os
import platform


def init():
    os.system("git submodule update --init --recursive")
    system = platform.system()
    if system == "Windows":
        os.system(".\\pc\\src\\gui\\SDL_ttf\\external\\Get-GitModules.ps1")
    else:
        os.system("./pc/src/gui/SDL_ttf/external/download.sh")
        os.system("./pico/install_toolchain")

    os.chdir("pico/picotool")
    if not os.path.exists("build"):
        os.mkdir("build")
    os.chdir("build")

    if system == "Windows":
        os.system("cmake .. -G \"MinGW Makefiles\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\\..\\tools\\picotool -DCMAKE_FLAT_INSTALL=1")
        os.system("make")
        os.sysmtem("make install")
    else:
        os.system("cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../tools/picotool -DCMAKE_FLAT_INSTALL=1")
        os.system("ninja -j4")
        os.system("ninja install")


if __name__ == '__main__':
    init()
