#!/bin/zsh

TOOLCHAIN_URL="https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=D484B37FF37D6FC3597EBE2877FB666A41D5253B"
mkdir -p tools/toolchain
wget -O /tmp/toolchain.tar.bz2 "$TOOLCHAIN_URL"
tar -C tools/toolchain --strip-components=1 -xjf /tmp/toolchain.tar.bz2
rm /tmp/toolchain.tar.bz2
